---
title: "Score Report"
format: docx
toc: true
params:
  program_name: NA
  data_file_path:
  
  # If adding more or different parameters (e.g., Year, Semester) will need to add to or change the params list.
---

```{r setup, include=FALSE}
#| warning: FALSE
#| message: FALSE

knitr::opts_chunk$set(error=FALSE)

options(digits = 3) # Setting the number of digits for the entire document

required_packages <- c("tidyverse", "ggplot2", "htmlTable", "openxlsx", "flextable", "psych", "stringr")

# Call packages
for (pkg in required_packages) {
    library(pkg, character.only = TRUE)
}
```

```{r Identifying Program, include=FALSE}
program <- params$program_name
```

```{r DateBlock, message=FALSE}
#| echo: FALSE
#| eval: TRUE

Analysis <- print(paste("This analysis was conducted on", program, "data"))

current_date <- format(Sys.Date(), "%B %d, %Y")

#Date <- print(paste0("This Report was generated on ", current_date))

```

This report was generated on `{r} current_date` for `{r} program`.  

```{r Total}
#| echo: FALSE

#Read in the data

data <- read.xlsx("./Data/Data_Large.xlsx")

#Filter by program
filtered_data <- data |>
  filter(Program == program)

#Make a total score
filtered_data$total <- rowSums(filtered_data[5:16])

```

The average score for all `{r} program` students was `{r} mean(filtered_data$total)`.  

```{r Cleaning up Global Environment, include=FALSE}
rm(list = ls()[sapply(mget(ls()), is.data.frame)])
rm(ft, p, new_columns)
```
